version: '3'

services:
  main:
    image: .

  mongo:
    image: 'mongo:4.0-xenial'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: development
    ports:
      - 27017:27017
